### ISSUE TITLE
Voting Functionality on GameSubmission

### ISSUE THREAD

**Issue by Figo2003** [sopra-fs24-group-12/PeekSeek-client#20]
- [x] Select submission that should win
- [x] Vote for that submission with button
- [x] Select submissions, which should be banned
- [x] Create UI for button and submission

**Comment by Arche1ion** [comment]
https://github.com/sopra-fs24-group-12/PeekSeek-server/commit/34ff3eab93cc2bbb22b7757da55cc482ff898a0e

**Comment by emmge** [comment]
clsoed https://github.com/sopra-fs24-group-12/PeekSeek-client/commit/20dda30248d482f4bd928dcaadfa92fb1a1dec5a
