### ISSUE TITLE
GameSummary API calls for winning submissions

### ISSUE THREAD

**Issue by Figo2003** [sopra-fs24-group-12/PeekSeek-client#29]
- [ ] Redirection to new page with google maps location of winning submission

**Comment by emmge** [comment]
closed https://github.com/sopra-fs24-group-12/PeekSeek-server/commit/f3ddadd02b486674f4830f73542debf65e62045d
https://github.com/sopra-fs24-group-12/PeekSeek-server/commit/81b12fab6fc04cc0cfe6e189ffa692d90380cdce

**Comment by emmge** [comment]
closed https://github.com/sopra-fs24-group-12/PeekSeek-client/commit/e5ae0dadd872594631b28997e2d1462d80e3388d
