### ISSUE TITLE
work on general design (.scss files)

### ISSUE THREAD

**Issue by asirimece** [sopra-fs24-group-12/PeekSeek-client#30]
- [x] Look into how to use and import NextUI library
- [x] Look into builder.io
- [x] create structure of style file

**Comment by silvanschlegel** [comment]
- [ ] Look into how to import and use Next UI library
- [ ] Look into builder.io
- [ ] create structure of style file

**Comment by silvanschlegel** [comment]
https://github.com/sopra-fs24-group-12/PeekSeek-client/compare/0dacd8129b46d9d4e339bc3f94ab6557591cb22a...01e83eecdea1f2e0feec4600a5accb2e4b1b5dc0

**Comment by silvanschlegel** [comment]
https://github.com/sopra-fs24-group-12/PeekSeek-client/compare/85f7c2be44126f6d04c12811be925ae348856bf6...0c7fb30806f7d6b4b4dee482909cdb9f274000b3

**Comment by asirimece** [comment]
7526d3f;
