### ISSUE TITLE
GamePage functionality

### ISSUE THREAD

**Issue by Arche1ion** [sopra-fs24-group-12/PeekSeek-client#93]
- [x] #94
- [x] #95
- [x] #96
- [x] #97
- [x] #98
- [x] #99
- [x] #100

**Comment by Arche1ion** [comment]
https://github.com/sopra-fs24-group-12/PeekSeek-client/commit/1873f8313fa3faf02272d71f41ae09acbd184739

**Comment by silvanschlegel** [comment]
https://github.com/sopra-fs24-group-12/PeekSeek-client/compare/a1e806f14dbf7edd008e1b6e37e7f27d37205b08...a3008ef1be072bb90ecb5437ec1f2085585f1865
Worked together with @Arche1ion on this equally.
