### ISSUE TITLE
API calls for submissions

### ISSUE THREAD

**Issue by Arche1ion** [sopra-fs24-group-12/PeekSeek-client#98]

**Comment by Arche1ion** [comment]
https://github.com/sopra-fs24-group-12/PeekSeek-client/commit/1873f8313fa3faf02272d71f41ae09acbd184739

**Comment by silvanschlegel** [comment]
https://github.com/sopra-fs24-group-12/PeekSeek-client/compare/1873f8313fa3faf02272d71f41ae09acbd184739...983b097560925f51c336580ee2a60b06d5580337
Worked together with @Arche1ion on this equally.
